name: github-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Use auto to auto calculate version
        default: auto
        required: false
        type: string

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@c60129fdec11c0ced690c6f35fb37dcb488e63f4 # 2.0.44
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
