name: github-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Use auto to auto calculate version
        default: auto
        required: false
        type: string

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@fb06128e939b3c347883b4a369d4bba39011ce0b # 2.0.60
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
